;!knitout-2
;;Carriers: 1 2 3 4 5 6
;;Machine: swg
rack 0.5
inhook 1
tuck - b59 1
tuck - b57 1
tuck - b55 1
tuck - b53 1
tuck - b51 1
tuck - b49 1
tuck - b47 1
tuck - b45 1
tuck - b43 1
tuck - b41 1
tuck - b39 1
tuck - b37 1
tuck - b35 1
tuck - b33 1
tuck - b31 1
tuck - b29 1
tuck - b27 1
tuck - b25 1
tuck - b23 1
tuck - b21 1
tuck - b19 1
tuck - b17 1
tuck - b15 1
tuck - b13 1
tuck - b11 1
tuck - b9 1
tuck - b7 1
tuck - b5 1
tuck - b3 1
tuck - b1 1
releasehook 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck + f44 1
tuck + f46 1
tuck + f48 1
tuck + f50 1
tuck + f52 1
tuck + f54 1
tuck + f56 1
tuck + f58 1
xfer f58 b58
xfer b51 f51
xfer f46 b46
xfer b39 f39
xfer f34 b34
xfer b27 f27
xfer f22 b22
xfer b15 f15
xfer f10 b10
xfer b3 f3
knit - b59 1
knit - b58 1
knit - b57 1
knit - f56 1
knit - b55 1
knit - f54 1
knit - b53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - b49 1
knit - f48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - f44 1
knit - b43 1
knit - f42 1
knit - b41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
knit - f59 1
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
knit - b54 1
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
knit - f47 1
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
knit - b42 1
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
knit - f35 1
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
knit - b30 1
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
knit - f23 1
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
knit - b18 1
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + f0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
knit + f11 1
knit + f12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
knit + b18 1
knit + b19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
knit + f23 1
knit + f24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
knit + b30 1
knit + b31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
knit + f35 1
knit + f36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
knit + b42 1
knit + b43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
knit + f47 1
knit + f48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
knit + b54 1
knit + b55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
knit - b56 1
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
knit - f49 1
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
knit - b44 1
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
knit - f37 1
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
knit - b32 1
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
knit - f25 1
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
knit - b20 1
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
knit + b0 1
knit + f1 1
knit + f2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
knit + b8 1
knit + b9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
knit + f13 1
knit + f14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
knit + b20 1
knit + b21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
knit + f25 1
knit + f26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
knit + b32 1
knit + b33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
knit + f37 1
knit + f38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
knit + b44 1
knit + b45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
knit + f49 1
knit + f50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
knit + b56 1
knit + b57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
knit - b58 1
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
knit - f51 1
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
knit - b46 1
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
knit - f39 1
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
knit - b34 1
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
knit - f27 1
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
knit - b22 1
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
knit - b10 1
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
knit + f3 1
knit + f4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
knit + b11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
knit + f15 1
knit + f16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
knit + b22 1
knit + b23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
knit + f27 1
knit + f28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
knit + b34 1
knit + b35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
knit + f39 1
knit + f40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
knit + b46 1
knit + b47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
knit + f51 1
knit + f52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
knit + b58 1
knit + b59 1
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
knit - f53 1
knit - f52 1
xfer f51 b51
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
knit - b48 1
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
knit - f41 1
knit - f40 1
xfer f39 b39
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
knit - b36 1
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
knit - f29 1
knit - f28 1
xfer f27 b27
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
knit - b24 1
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
xfer f15 b15
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
knit - b12 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
knit - b0 1
knit + b0 1
knit + b1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + f6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
knit + b12 1
knit + b13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
xfer f16 b16
knit + b16 1
knit + f17 1
knit + f18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
knit + b24 1
knit + b25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
xfer f28 b28
knit + b28 1
knit + f29 1
knit + f30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
knit + b36 1
knit + b37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
xfer f40 b40
knit + b40 1
knit + f41 1
knit + f42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
knit + b48 1
knit + b49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
xfer f52 b52
knit + b52 1
knit + f53 1
knit + f54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
xfer f57 b57
knit - b57 1
xfer b56 f56
knit - f56 1
knit - f55 1
knit - f54 1
xfer f53 b53
knit - b53 1
xfer b52 f52
knit - f52 1
xfer f51 b51
knit - b51 1
knit - b50 1
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
xfer f45 b45
knit - b45 1
xfer b44 f44
knit - f44 1
knit - f43 1
knit - f42 1
xfer f41 b41
knit - b41 1
xfer b40 f40
knit - f40 1
xfer f39 b39
knit - b39 1
knit - b38 1
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
xfer f33 b33
knit - b33 1
xfer b32 f32
knit - f32 1
knit - f31 1
knit - f30 1
xfer f29 b29
knit - b29 1
xfer b28 f28
knit - f28 1
xfer f27 b27
knit - b27 1
knit - b26 1
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
xfer f21 b21
knit - b21 1
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
xfer f17 b17
knit - b17 1
xfer b16 f16
knit - f16 1
xfer f15 b15
knit - b15 1
knit - b14 1
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
xfer f5 b5
knit - b5 1
xfer b4 f4
knit - f4 1
xfer f3 b3
knit - b3 1
knit - b2 1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
knit + b2 1
knit + b3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
xfer f10 b10
knit + b10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
knit + b14 1
knit + b15 1
xfer f16 b16
knit + b16 1
xfer b17 f17
knit + f17 1
xfer f18 b18
knit + b18 1
knit + f19 1
knit + f20 1
xfer b21 f21
knit + f21 1
xfer f22 b22
knit + b22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
knit + b26 1
knit + b27 1
xfer f28 b28
knit + b28 1
xfer b29 f29
knit + f29 1
xfer f30 b30
knit + b30 1
knit + f31 1
knit + f32 1
xfer b33 f33
knit + f33 1
xfer f34 b34
knit + b34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
knit + b38 1
knit + b39 1
xfer f40 b40
knit + b40 1
xfer b41 f41
knit + f41 1
xfer f42 b42
knit + b42 1
knit + f43 1
knit + f44 1
xfer b45 f45
knit + f45 1
xfer f46 b46
knit + b46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
knit + b50 1
knit + b51 1
xfer f52 b52
knit + b52 1
xfer b53 f53
knit + f53 1
xfer f54 b54
knit + b54 1
knit + f55 1
knit + f56 1
xfer b57 f57
knit + f57 1
xfer f58 b58
knit + b58 1
xfer b59 f59
knit + f59 1
xfer f59 b59
knit - b59 1
xfer b58 f58
knit - f58 1
knit - f57 1
knit - f56 1
xfer f55 b55
knit - b55 1
xfer b54 f54
knit - f54 1
xfer f53 b53
knit - b53 1
knit - b52 1
knit - b51 1
xfer b50 f50
knit - f50 1
xfer f49 b49
knit - b49 1
xfer b48 f48
knit - f48 1
xfer f47 b47
knit - b47 1
xfer b46 f46
knit - f46 1
knit - f45 1
knit - f44 1
xfer f43 b43
knit - b43 1
xfer b42 f42
knit - f42 1
xfer f41 b41
knit - b41 1
knit - b40 1
knit - b39 1
xfer b38 f38
knit - f38 1
xfer f37 b37
knit - b37 1
xfer b36 f36
knit - f36 1
xfer f35 b35
knit - b35 1
xfer b34 f34
knit - f34 1
knit - f33 1
knit - f32 1
xfer f31 b31
knit - b31 1
xfer b30 f30
knit - f30 1
xfer f29 b29
knit - b29 1
knit - b28 1
knit - b27 1
xfer b26 f26
knit - f26 1
xfer f25 b25
knit - b25 1
xfer b24 f24
knit - f24 1
xfer f23 b23
knit - b23 1
xfer b22 f22
knit - f22 1
knit - f21 1
knit - f20 1
xfer f19 b19
knit - b19 1
xfer b18 f18
knit - f18 1
xfer f17 b17
knit - b17 1
knit - b16 1
knit - b15 1
xfer b14 f14
knit - f14 1
xfer f13 b13
knit - b13 1
xfer b12 f12
knit - f12 1
xfer f11 b11
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - b4 1
knit - b3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
xfer f0 b0
knit + b0 1
xfer b1 f1
knit + f1 1
xfer f2 b2
knit + b2 1
xfer b3 f3
knit + f3 1
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + f9 1
knit + f10 1
xfer b11 f11
knit + f11 1
xfer f12 b12
knit + b12 1
xfer b13 f13
knit + f13 1
xfer f14 b14
knit + b14 1
xfer b15 f15
knit + f15 1
knit + b16 1
knit + b17 1
xfer f18 b18
knit + b18 1
xfer b19 f19
knit + f19 1
xfer f20 b20
knit + b20 1
knit + f21 1
knit + f22 1
xfer b23 f23
knit + f23 1
xfer f24 b24
knit + b24 1
xfer b25 f25
knit + f25 1
xfer f26 b26
knit + b26 1
xfer b27 f27
knit + f27 1
knit + b28 1
knit + b29 1
xfer f30 b30
knit + b30 1
xfer b31 f31
knit + f31 1
xfer f32 b32
knit + b32 1
knit + f33 1
knit + f34 1
xfer b35 f35
knit + f35 1
xfer f36 b36
knit + b36 1
xfer b37 f37
knit + f37 1
xfer f38 b38
knit + b38 1
xfer b39 f39
knit + f39 1
knit + b40 1
knit + b41 1
xfer f42 b42
knit + b42 1
xfer b43 f43
knit + f43 1
xfer f44 b44
knit + b44 1
knit + f45 1
knit + f46 1
xfer b47 f47
knit + f47 1
xfer f48 b48
knit + b48 1
xfer b49 f49
knit + f49 1
xfer f50 b50
knit + b50 1
xfer b51 f51
knit + f51 1
knit + b52 1
knit + b53 1
xfer f54 b54
knit + b54 1
xfer b55 f55
knit + f55 1
xfer f56 b56
knit + b56 1
knit + f57 1
knit + f58 1
xfer b59 f59
knit + f59 1
outhook 1
drop f0
drop b0
drop f1
drop b1
drop f2
drop b2
drop f3
drop b3
drop f4
drop b4
drop f5
drop b5
drop f6
drop b6
drop f7
drop b7
drop f8
drop b8
drop f9
drop b9
drop f10
drop b10
drop f11
drop b11
drop f12
drop b12
drop f13
drop b13
drop f14
drop b14
drop f15
drop b15
drop f16
drop b16
drop f17
drop b17
drop f18
drop b18
drop f19
drop b19
drop f20
drop b20
drop f21
drop b21
drop f22
drop b22
drop f23
drop b23
drop f24
drop b24
drop f25
drop b25
drop f26
drop b26
drop f27
drop b27
drop f28
drop b28
drop f29
drop b29
drop f30
drop b30
drop f31
drop b31
drop f32
drop b32
drop f33
drop b33
drop f34
drop b34
drop f35
drop b35
drop f36
drop b36
drop f37
drop b37
drop f38
drop b38
drop f39
drop b39
drop f40
drop b40
drop f41
drop b41
drop f42
drop b42
drop f43
drop b43
drop f44
drop b44
drop f45
drop b45
drop f46
drop b46
drop f47
drop b47
drop f48
drop b48
drop f49
drop b49
drop f50
drop b50
drop f51
drop b51
drop f52
drop b52
drop f53
drop b53
drop f54
drop b54
drop f55
drop b55
drop f56
drop b56
drop f57
drop b57
drop f58
drop b58
drop f59
drop b59
