;!knitout-2
;;Carriers: 1 2 3 4 5 6
;;Machine: swg
rack 0.5
inhook 1
tuck - b11 1
tuck - b9 1
tuck - b7 1
tuck - b5 1
tuck - b3 1
tuck - b1 1
releasehook 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
xfer f10 b10
xfer b3 f3
knit - b11 1
knit - b10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer b7 f7
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer f2 b2
knit - b2 1
knit - b1 1
knit - f0 1
knit + b0 1
xfer f1 b1
knit + b1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + f5 1
xfer b6 f6
knit + f6 1
knit + f7 1
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
xfer b5 f5
knit - f5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
xfer f0 b0
knit - b0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit - b11 1
knit - b10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
knit - f3 1
xfer b2 f2
knit - f2 1
xfer f1 b1
knit - b1 1
xfer b0 f0
knit - f0 1
knit + b0 1
xfer b1 f1
knit + f1 1
knit + f2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
knit + b9 1
knit + b10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
knit - b8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
xfer b2 f2
knit - f2 1
xfer b1 f1
knit - f1 1
knit - f0 1
xfer b0 f0
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
xfer b5 f5
knit + f5 1
xfer f6 b6
knit + b6 1
knit + b7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
xfer b11 f11
knit - f11 1
xfer b10 f10
knit - f10 1
xfer f9 b9
knit - b9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
knit - b6 1
xfer f5 b5
knit - b5 1
knit - f4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
knit + f3 1
xfer f4 b4
knit + b4 1
knit + b5 1
xfer f6 b6
knit + b6 1
xfer b7 f7
knit + f7 1
xfer f8 b8
knit + b8 1
xfer b9 f9
knit + f9 1
xfer b10 f10
knit + f10 1
xfer b11 f11
knit + f11 1
knit - b11 1
xfer b10 f10
knit - f10 1
knit - f9 1
xfer b8 f8
knit - f8 1
xfer f7 b7
knit - b7 1
xfer b6 f6
knit - f6 1
knit - b5 1
xfer f4 b4
knit - b4 1
xfer f3 b3
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
knit + b0 1
knit + f1 1
knit + b2 1
xfer f3 b3
knit + b3 1
xfer f4 b4
knit + b4 1
knit + f5 1
knit + b6 1
xfer b7 f7
knit + f7 1
knit + f8 1
xfer b9 f9
knit + f9 1
knit + b10 1
xfer b11 f11
knit + f11 1
outhook 1
drop f0
drop b0
drop f1
drop b1
drop f2
drop b2
drop f3
drop b3
drop f4
drop b4
drop f5
drop b5
drop f6
drop b6
drop f7
drop b7
drop f8
drop b8
drop f9
drop b9
drop f10
drop b10
drop f11
drop b11
