;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: swg
;;Position: Center
rack 0.25
in 1
tuck - b23 1
tuck - f23 1
tuck - b22 1
tuck - f22 1
tuck - b21 1
tuck - f21 1
tuck - f20 1
tuck - b19 1
tuck - f19 1
tuck - b18 1
tuck - f18 1
tuck - b17 1
tuck - f17 1
tuck - b16 1
tuck - b15 1
tuck - f15 1
tuck - b14 1
tuck - f14 1
tuck - b13 1
tuck - f13 1
tuck - f12 1
tuck - b11 1
tuck - f11 1
tuck - b10 1
tuck - f10 1
tuck - b9 1
tuck - f9 1
tuck - b8 1
tuck - b7 1
tuck - f7 1
tuck - b6 1
tuck - f6 1
tuck - b5 1
tuck - f5 1
tuck - f4 1
tuck - b3 1
tuck - f3 1
tuck - b2 1
tuck - f2 1
tuck - b1 1
tuck - f1 1
tuck - b0 1
x-speed-number 10
tuck + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
tuck + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
tuck + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
tuck + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
tuck + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
tuck + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b21 f21
xfer f17 b17
xfer b13 f13
xfer f9 b9
xfer b5 f5
xfer f1 b1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
tuck - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
tuck - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
tuck - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
tuck - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
tuck - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
tuck - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer f2 b2
xfer b6 f6
xfer f10 b10
xfer b14 f14
xfer f18 b18
xfer b22 f22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
tuck + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
tuck + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
tuck + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
tuck + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
tuck + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
tuck + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b23 f23
xfer f19 b19
xfer b15 f15
xfer f11 b11
xfer b7 f7
xfer f3 b3
rack 0.25
x-speed-number 10
tuck - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
tuck - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
tuck - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
tuck - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
tuck - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
tuck - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b0 f0
xfer f4 b4
xfer b8 f8
xfer f12 b12
xfer b16 f16
xfer f20 b20
rack 0.25
x-speed-number 10
knit + f0 1
tuck + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
tuck + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
tuck + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
tuck + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
tuck + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
tuck + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f21 b21
xfer b17 f17
xfer f13 b13
xfer b9 f9
xfer f5 b5
xfer b1 f1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
tuck - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
tuck - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
tuck - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
tuck - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
tuck - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
tuck - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b2 f2
xfer f6 b6
xfer b10 f10
xfer f14 b14
xfer b18 f18
xfer f22 b22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
tuck + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
tuck + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
tuck + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
tuck + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
tuck + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
tuck + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f23 b23
xfer b19 f19
xfer f15 b15
xfer b11 f11
xfer f7 b7
xfer b3 f3
rack 0.25
x-speed-number 10
knit - b23 1
tuck - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
tuck - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
tuck - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
tuck - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
tuck - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
tuck - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer f0 b0
xfer b4 f4
xfer f8 b8
xfer b12 f12
xfer f16 b16
xfer b20 f20
rack 0.25
x-speed-number 10
tuck + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
tuck + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
tuck + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
tuck + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
tuck + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
tuck + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b21 f21
xfer f17 b17
xfer b13 f13
xfer f9 b9
xfer b5 f5
xfer f1 b1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
tuck - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
tuck - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
tuck - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
tuck - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
tuck - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
tuck - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer f2 b2
xfer b6 f6
xfer f10 b10
xfer b14 f14
xfer f18 b18
xfer b22 f22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
tuck + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
tuck + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
tuck + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
tuck + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
tuck + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
tuck + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b23 f23
xfer f19 b19
xfer b15 f15
xfer f11 b11
xfer b7 f7
xfer f3 b3
rack 0.25
x-speed-number 10
tuck - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
tuck - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
tuck - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
tuck - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
tuck - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
tuck - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b0 f0
xfer f4 b4
xfer b8 f8
xfer f12 b12
xfer b16 f16
xfer f20 b20
rack 0.25
x-speed-number 10
knit + f0 1
tuck + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
tuck + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
tuck + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
tuck + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
tuck + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
tuck + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f21 b21
xfer b17 f17
xfer f13 b13
xfer b9 f9
xfer f5 b5
xfer b1 f1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
tuck - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
tuck - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
tuck - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
tuck - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
tuck - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
tuck - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b2 f2
xfer f6 b6
xfer b10 f10
xfer f14 b14
xfer b18 f18
xfer f22 b22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
tuck + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
tuck + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
tuck + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
tuck + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
tuck + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
tuck + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f23 b23
xfer b19 f19
xfer f15 b15
xfer b11 f11
xfer f7 b7
xfer b3 f3
rack 0.25
x-speed-number 10
knit - b23 1
tuck - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
tuck - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
tuck - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
tuck - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
tuck - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
tuck - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer f0 b0
xfer b4 f4
xfer f8 b8
xfer b12 f12
xfer f16 b16
xfer b20 f20
rack 0.25
x-speed-number 10
tuck + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
tuck + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
tuck + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
tuck + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
tuck + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
tuck + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b21 f21
xfer f17 b17
xfer b13 f13
xfer f9 b9
xfer b5 f5
xfer f1 b1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
tuck - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
tuck - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
tuck - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
tuck - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
tuck - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
tuck - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer f2 b2
xfer b6 f6
xfer f10 b10
xfer b14 f14
xfer f18 b18
xfer b22 f22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
tuck + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
tuck + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
tuck + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
tuck + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
tuck + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
tuck + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer b23 f23
xfer f19 b19
xfer b15 f15
xfer f11 b11
xfer b7 f7
xfer f3 b3
rack 0.25
x-speed-number 10
tuck - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
tuck - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
tuck - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
tuck - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
tuck - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
tuck - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b0 f0
xfer f4 b4
xfer b8 f8
xfer f12 b12
xfer b16 f16
xfer f20 b20
rack 0.25
x-speed-number 10
knit + f0 1
tuck + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
knit + b2 1
knit + f3 1
knit + b3 1
tuck + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
knit + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
tuck + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
knit + b10 1
knit + f11 1
knit + b11 1
tuck + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
tuck + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
tuck + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f21 b21
xfer b17 f17
xfer f13 b13
xfer b9 f9
xfer f5 b5
xfer b1 f1
rack 0.25
x-speed-number 10
knit - b23 1
knit - f23 1
knit - b22 1
knit - f22 1
knit - b21 1
tuck - f21 1
knit - b20 1
knit - f20 1
knit - b19 1
knit - f19 1
knit - b18 1
knit - f18 1
tuck - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - f15 1
knit - b14 1
knit - f14 1
knit - b13 1
tuck - f13 1
knit - b12 1
knit - f12 1
knit - b11 1
knit - f11 1
knit - b10 1
knit - f10 1
tuck - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - f7 1
knit - b6 1
knit - f6 1
knit - b5 1
tuck - f5 1
knit - b4 1
knit - f4 1
knit - b3 1
knit - f3 1
knit - b2 1
knit - f2 1
tuck - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
rack 0.0
xfer b2 f2
xfer f6 b6
xfer b10 f10
xfer f14 b14
xfer b18 f18
xfer f22 b22
rack 0.25
x-speed-number 10
knit + f0 1
knit + b0 1
knit + f1 1
knit + b1 1
knit + f2 1
tuck + b2 1
knit + f3 1
knit + b3 1
knit + f4 1
knit + b4 1
knit + f5 1
knit + b5 1
tuck + f6 1
knit + b6 1
knit + f7 1
knit + b7 1
knit + f8 1
knit + b8 1
knit + f9 1
knit + b9 1
knit + f10 1
tuck + b10 1
knit + f11 1
knit + b11 1
knit + f12 1
knit + b12 1
knit + f13 1
knit + b13 1
tuck + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
tuck + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
tuck + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
x-speed-number 3
rack 0.0
xfer f23 b23
xfer b19 f19
xfer f15 b15
xfer b11 f11
xfer f7 b7
xfer b3 f3
rack 0.25
x-speed-number 10
knit - b23 1
knit - b22 1
knit - f22 1
knit - b21 1
knit - f21 1
knit - b20 1
knit - f20 1
knit - f19 1
knit - b18 1
knit - f18 1
knit - b17 1
knit - f17 1
knit - b16 1
knit - f16 1
knit - b15 1
knit - b14 1
knit - f14 1
knit - b13 1
knit - f13 1
knit - b12 1
knit - f12 1
knit - f11 1
knit - b10 1
knit - f10 1
knit - b9 1
knit - f9 1
knit - b8 1
knit - f8 1
knit - b7 1
knit - b6 1
knit - f6 1
knit - b5 1
knit - f5 1
knit - b4 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f2 1
knit - b1 1
knit - f1 1
knit - b0 1
knit - f0 1
x-speed-number 3
out 1
drop f0
drop b0
drop f1
drop b1
drop f2
drop b2
drop f3
drop b3
drop f4
drop b4
drop f5
drop b5
drop f6
drop b6
drop f7
drop b7
drop f8
drop b8
drop f9
drop b9
drop f10
drop b10
drop f11
drop b11
drop f12
drop b12
drop f13
drop b13
drop f14
drop b14
drop f15
drop b15
drop f16
drop b16
drop f17
drop b17
drop f18
drop b18
drop f19
drop b19
drop f20
drop b20
drop f21
drop b21
drop f22
drop b22
drop f23
drop b23
